# Generated by Django 6.0.3 on 2026-03-20 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=10)),
                ("title", models.CharField(max_length=500)),
                ("summary", models.TextField(blank=True)),
                ("url", models.URLField(max_length=500, unique=True)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ticker", "published_at"],
                        name="api_newsart_ticker_1dee26_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ScrapedPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("reddit", "Reddit"), ("stocktwits", "StockTwits")],
                        max_length=50,
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=10)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("content", models.TextField()),
                ("author", models.CharField(blank=True, max_length=100)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("engagement_score", models.FloatField(default=0)),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("subreddit", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField()),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ticker", "created_at"],
                        name="api_scraped_ticker_7cea99_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SentimentAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=10)),
                (
                    "overall_sentiment",
                    models.CharField(
                        choices=[
                            ("bullish", "Bullish"),
                            ("bearish", "Bearish"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence_score", models.FloatField()),
                ("reasoning", models.TextField(blank=True)),
                ("key_points", models.JSONField(default=list)),
                ("risk_factors", models.JSONField(default=list)),
                ("predicted_trend", models.CharField(blank=True, max_length=20)),
                ("recommendation", models.CharField(blank=True, max_length=20)),
                ("reddit_posts_count", models.IntegerField(default=0)),
                ("news_articles_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ticker", "created_at"],
                        name="api_sentime_ticker_34aa9a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WatchlistTicker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("last_analyzed", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "ticker")},
            },
        ),
    ]
